### ISSUE TITLE
Can't build the repository

### ISSUE THREAD

**Issue by Gabriel-la-flamboyance** [gezp/universal_robot_ign#1]
Hello sir, I am having an issue building this repository. 
When I make "**colcon build**", i get at the end : 
**Summary: 0 packages finished [4.05s]
  1 package failed: universal_robot_ign
  1 package had stderr output: universal_robot_ign**

Can you help me please.

**Comment by gezp** [comment]
can you give me more detials ? the version of ros2 and ignition gazebo you used, and what is the output error of building?

**Comment by Gabriel-la-flamboyance** [comment]
I have used the ROS 1 and gazebo version 9, when I build i get this : 
**Starting >>> universal_robot_ign
--- stderr: universal_robot_ign                         
CMake Error at CMakeLists.txt:12 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake" with
  any of the following names:

    ament_cmakeConfig.cmake
    ament_cmake-config.cmake

  Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
  "ament_cmake_DIR" to a directory containing one of the above files.  If
  "ament_cmake" provides a separate development package or SDK, be sure it
  has been installed.


---
Failed   <<< universal_robot_ign [5.12s, exited with code 1]

Summary: 0 packages finished [5.83s]
  1 package failed: universal_robot_ign
  1 package had stderr output: universal_robot_ign**

**Comment by gezp** [comment]
This package is based on **ROS2 (Foxy)** and **Ignition Gazebo (Dome)** , so you can't use this package for your project. 
by the way, there are many repo  in GitHub based on ROS1 and  Classical Gazebo for universal robot simulation , you can try use them.

**Comment by Gabriel-la-flamboyance** [comment]
Ok, thanks by the way, your repository is so well done.
